### ISSUE TITLE
continue show wait , On the server webrtc  don`t jump to record

### ISSUE THREAD

**Issue by sankexin** [freddyaboulton/gradio-webrtc#17]
when On the server and use a local browser(Local PC can be used normally)

py10   gradio_webrtc[vad]==0.0.12    gradio==5.5.0

```
audio = WebRTC(
  label="Stream",
  rtc_configuration=rtc_configuration,
  mode="send-receive",
  modality="audio",
  )
```

![image](https://github.com/user-attachments/assets/af6e7c66-faf4-4392-bd71-50a6b9818aa2)

 hou to fix the bug?

**Comment by yzmyyff** [comment]
the same issue... Could you give some advice? @freddyaboulton

**Comment by freddyaboulton** [comment]
Hi @sankexin @yzmyyff - did you set up the TURN server? https://github.com/freddyaboulton/gradio-webrtc?tab=readme-ov-file#deployment

**Comment by freddyaboulton** [comment]
Hi all, you need to use a TURN server for the webRTC connection to be established. I prepared a guide that walks through using twilio's free servers and also self-hosting:

https://freddyaboulton.github.io/gradio-webrtc/deployment/
