### ISSUE TITLE
Issues encountered while running the demo on a remote machine.

### ISSUE THREAD

**Issue by JeoJava** [freddyaboulton/gradio-webrtc#18]
I ran demo.py on a remote machine and accessed the Gradio shared link locally (with share=True). After I input the audio, it keeps showing as "waiting."  

### env
gradio                         5.0.0
gradio_client                  1.4.0
gradio_webrtc                  0.0.12

### code

[demo.py ](https://huggingface.co/spaces/freddyaboulton/mini-omni2-webrtc/blob/main/app.py)

### gradio_rtc log

![image](https://github.com/user-attachments/assets/71e38ce7-f3f7-489e-b606-7fe3638b9426)

### gradio ui (wating always )
![image](https://github.com/user-attachments/assets/da6f6d4a-0b75-4950-bc2c-e3302e8a08c6)

**Comment by freddyaboulton** [comment]
HI @JeoJava - did you set up the TURN server? 
https://github.com/freddyaboulton/gradio-webrtc?tab=readme-ov-file#deployment

**Comment by JeoJava** [comment]
> HI @JeoJava - did you set up the TURN server? https://github.com/freddyaboulton/gradio-webrtc?tab=readme-ov-file#deployment

this is my app :  https://huggingface.co/spaces/Xarey/gradio_webrct_demo/blob/main/app.py , can u help me ?

**Comment by freddyaboulton** [comment]
In the meantime please use the free servers provided with a twilio API account (no credit card needed I believe).

**Comment by JeoJava** [comment]
> Hi @JeoJava - the issue is that those google urls are for STUN servers. You need a TURN server for apps behind a firewall (spaces, etc). I think I will create a community TURN server so that users don't have to worry about this.

**that's great!** 
But, I set up a turn server with coturn, but it still doesn't work, it's my app。 and the server passed the test with [trickle-ice], why ? (https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/)
[app](https://huggingface.co/spaces/Xarey/demo1/blob/main/app.py)
