### ISSUE TITLE
How can I show whole conversation in gr.chatbot? More documentation is needed.

### ISSUE THREAD

**Issue by yzmyyff** [freddyaboulton/gradio-webrtc#19]
Hi @freddyaboulton 

Thanks for your great work!

can I show the whole conversation in `gr.chatbot`? I use `StreamHandler` to stream input and output but can't find a way to pass chatbot history

**Comment by freddyaboulton** [comment]
Hi @yzmyyff - thank you for the compliment!

You need to `yield AdditionalOutputs(...)` and add an `on_additional_outputs` event. Check out these demos

https://huggingface.co/spaces/freddyaboulton/talk-to-claude/blob/main/app.py#L102

https://huggingface.co/spaces/freddyaboulton/talk-to-qwen-webrtc/blob/c822b849b8061490afe3fa1e7093baacd27e101f/app.py#L71

**Comment by yzmyyff** [comment]
Great! It works!

**Comment by freddyaboulton** [comment]
Great @yzmyyff ! Please share your demo - would love to amplify on the gradio twitter account 😄

**Comment by yzmyyff** [comment]
So sorry for that... It's an internal project and is not authorized to be released

**Comment by freddyaboulton** [comment]
It's ok!
