### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Henry-23** [freddyaboulton/gradio-webrtc#2]
Hi freddyaboulton. Thanks for your great work. I have some questions.
1. What is the difference between this and streaming Image component in Gradio? 
2. Does the current work support the synchronization of images and audio in webrtc?

**Comment by freddyaboulton** [comment]
Hi @Henry-23 !

> What is the difference between this and streaming Image component in Gradio?

Under the hood this will establish a WebRTC connection between the client and server. The expectation is that the client sends over a frame from the webcam and the server sends back a transformed frame (the result of applying the `fn` used in the `stream` event of this component). WebRTC is much faster than the image streaming component in core gradio but it comes with downsides. One of the biggest is that WebRTC is harder to deploy. In cloud environments like Spaces/EC2 etc you'll have to set up a TURN server or get one from an API provider. That's what's happening here: https://huggingface.co/spaces/freddyaboulton/webrtc/blob/f62d389d6f78701f2d167ee2592a426513c349f1/app.py#L15 In general I recommend using the streaming features in gradio core first and if that's not good enough try this component.

> Does the current work support the synchronization of images and audio in webrtc?

Not sure what this means. But right now it only supports image in / image out. I would like audio to work in the future though.

**Comment by Henry-23** [comment]
Hi @freddyaboulton! 

Thanks for your reply. I previously raised an issue about video streaming mode under Gradio 5.0 dev, where I mentioned that the feature I need is synchronized streaming of audio and video. I've tested this in Gradio core, and there is a likelihood of experiencing delays and audio-video synchronization issues. 

So, if the upcoming WebRTC project can integrate audio and image in/out functionalities, that would be fantastic and would greatly solve my problem. I look forward to future updates!
