### ISSUE TITLE
Webcam resolution

### ISSUE THREAD

**Issue by kianwei96** [freddyaboulton/gradio-webrtc#26]
Thanks for the work thus far, the feed is incredibly smooth compared to the default gr.image component!

I noticed that I'm able to get 1440x1920 images from my iPhone's back webcam using gr.Image, but am only getting 480x640 using the WebRTC equivalent. Occasionally, the feed automatically drops down to an even lower resolution (around 300+px). Hoping to be able to stream better quality images (for tracking), or at least at a fixed resolution, wonder if you have any ideas/advise?

**Comment by kianwei96** [comment]
Dear @freddyaboulton , thanks for the quick update! I just tested it out, but none of the constraints (min resolutions, max resolutions, frame rates) seem to be followed (also tried the simpler "facingMode" option, which ended up not being respected. 

Here's the relevant section:
![image](https://github.com/user-attachments/assets/6ad1579f-6cf4-40a9-9bea-ed412a216c2b)

Perhaps on a related note, I seem to be getting these warnings from (I think) ffmpeg, regardless of whether constraints were specified:
![image](https://github.com/user-attachments/assets/5e42c30c-156b-4a56-bea3-9610e665952c)

I'm testing with an iPhone 15 back camera, and the server with:
aiortc==1.9.0
gradio==5.6.0
gradio_client==1.4.3
gradio_webrtc==0.0.14

If you're able to provide a minimal working example with versions etc, it'll be great for me to test on my end and narrow down the issues!

**Comment by freddyaboulton** [comment]
Hi @kianwei96 - it was a bug on my end. You can now set the constraints like this (as of version 0.0.15). Note the new `rtp_params` argument which is telling WebRTC to preserve the resolution no matter what. Sometimes it will recale images to maintain a higher framerate.

```python
            image = WebRTC(
                label="Stream", rtc_configuration=rtc_configuration,
                mode="send",
                track_constraints={"width": {"exact": 800},
                                   "height": {"exact": 600},
                                   "aspectRatio": {"exact": 1.33333}
                                   },
                rtp_params={"degradationPreference": "maintain-resolution"}
            )
```

**Comment by kianwei96** [comment]
@freddyaboulton  great! thanks for the quick update, I will test it out soon, looking forward to continuing to build off this component!
