### ISSUE TITLE
Does it support streaming Audio from the Client to the Server?

### ISSUE THREAD

**Issue by LiuShixing** [freddyaboulton/gradio-webrtc#27]
I need to receive audio stream (chunks) in the server, not a whole audio

**Comment by freddyaboulton** [comment]
Yes you can build your own StreamHandler. It should have a `receive` method that controls how each individual packet is handled: https://huggingface.co/spaces/freddyaboulton/talk-to-moshi/blob/main/app.py#L36

You can also use the built-in `ReplyOnPause` handler for convenience. The audio in this case will be the entire audio until the speaker paused but the stream is always kept open.

More information here: https://freddyaboulton.github.io/gradio-webrtc/user-guide/

**Comment by LiuShixing** [comment]
Thinks
