### ISSUE TITLE
updating state

### ISSUE THREAD

**Issue by kianwei96** [freddyaboulton/gradio-webrtc#36]
I'm back with another question! Would it be possible to implement multiple outputs for mode="send-receive", modality="video"? On top of calculating and visualizing object poses on a per frame basis, I think it would be nice to be able to cache the latest-n-poses somewhere, for common methods like Kalman filtering/Lerping. 

Currently the workaround might be to use globals, but that becomes ugly quickly (especially with multiple users). With multiple outputs we can just update the gr.State() to reflect the latest computed info/pose.

**Comment by freddyaboulton** [comment]
HI @kianwei96 - yes you can update a `gr.State` or any other gradio component by using `on_additional_outputs` event. You need to `yield AdditionalOutputs(...)` from within your generator. 

See the guide in the docs here: https://freddyaboulton.github.io/gradio-webrtc/user-guide/#additional-outputs

Example in `talk-to-qwen` where the chatbot mesage history is stored in `gr.State` and updated: https://huggingface.co/spaces/freddyaboulton/talk-to-qwen-webrtc/blob/c822b849b8061490afe3fa1e7093baacd27e101f/app.py#L105

Lots of other examples of this in the cookbook as well: https://freddyaboulton.github.io/gradio-webrtc/cookbook/
