### ISSUE TITLE
change this "Record" text to something else

### ISSUE THREAD

**Issue by luwei-nuaa** [freddyaboulton/gradio-webrtc#41]
Thank you for your excellent work. I have a small question. I noticed that when using gradio_webrtc for audio recording and transmission, the interface includes a microphone icon. When clicking this icon, a button appears, and the button displays the text "Record" on the front end. I would like to change this "Record" text to something else. How can I modify it?

**Comment by luwei-nuaa** [comment]
> Thank you for your excellent work. I have a small question. I noticed that when using gradio_webrtc for audio recording and transmission, the interface includes a microphone icon. When clicking this icon, a button appears, and the button displays the text "Record" on the front end. I would like to change this "Record" text to something else. How can I modify it

**Comment by freddyaboulton** [comment]
Did you figure it out? I am not sure if this is possible atm

**Comment by luwei-nuaa** [comment]
> Did you figure it out? I am not sure if this is possible atm

I modified all occurrences of audio.record in python3.10\Lib\site-packages\gradio_webrtc\templates\component\index.js, and this seems to work.

**Comment by freddyaboulton** [comment]
Ok, I'll make a note to make that parameter configurable so that it's easier!
